### PR TITLE
Fix extra spaces around the color token

### PR DESCRIPTION
**Pull request by quietshu**
Hi Stephen! This workaround should be a improvement of #457. But still a small defect is that it doesn't do perfect full-word match (GREENNNN). Looks all good except for this.

image

### CODE REVIEW

**Comment by quietshu** [comment]
Ohh you're right. Trying to fix that.

**Comment by increpare** [comment]
Ok, sorry, I tried using the 'change review' tool but I have no idea how it works.  Here's my comment:

Thanks for the pull request.  It's almost there, BUT it changes the behaviour of the parser so that whitespace is no longer required between colours, which means I can't accept it.  Can you fix it?

bildschirmfoto 2018-06-15 um 11 33 20

**Comment by quietshu** [comment]
Sure.

**Comment by quietshu** [comment]
fixed :))

image

**Comment by increpare** [comment]
It fails some unit tests (you can check these yourself by opening the tests/tests.html file)

here're two examples from it

this one is understandable enough because your code doesn't seem to work if there's whitespace at the start of the line
https://www.puzzlescript.net/editor.html?hack=0ae9041b660343c1eec135f9786ea4d1

this one, however, is spookier
https://www.puzzlescript.net/editor.html?hack=67e85b107e0331f251477c766139e0ea

(it renders a blank screen in your code, but works fine on puzzlescript.net)

**Comment by quietshu** [comment]
Oh sorry I didn't know about the tests/tests.html file.  
Will come up with some fixes later.

**Comment by quietshu** [comment]
For 2, changing background color to text color avoids handling cases like

image

so by removing those whitespace tokens at the beginning of lines, it now can pass all the unit tests.

**Comment by quietshu** [comment]
(working on feature 1 and 2)

**Comment by quietshu** [comment]
For 2: just added hsl and some contrast ratio stuff.

before:
image

after (#0F192A is same as the background color):
image

**Comment by increpare** [comment]
oops i accidentally merged an earlier version of this which I manually undid. just making a note because I'll have to be careful when remerging :)

**Comment by increpare** [comment]
looking good :)

**Comment by quietshu** [comment]
image

finally :)

**Comment by pfefferminzz** [comment]
Nice!

For the 5x5 sprites, i'd love to have the color in the background and the numbers in black, white or the editor background color, but Stephen already wrote on twitter he found it too jarring. ;(

**Pull request merged**
