### PR TITLE
Update node installation to automatically install the correct versions.

### LINKED ISSUE #955: Node build fails with 'illegal characters in path'
Here is the node install and command line:
`npm i rimraf compress-images web-resource-inliner ncp gifsicle@5.3.0 concat ycssmin terser gzipper html-minifier-terser glob`
`node compile.js `

Here is the full error trace:
```
Error: Illegal characters in path.
    at pathArg (d:\MyDocs\dev\Polyomino\PSForks\(increpare)PuzzleScript\node_modules\rimraf\dist\cjs\src\path-arg.js:45:33)
    at AsyncFunction.<anonymous> (d:\MyDocs\dev\Polyomino\PSForks\(increpare)PuzzleScript\node_modules\rimraf\dist\cjs\src\index.js:57:47)
    at d:\MyDocs\dev\Polyomino\PSForks\(increpare)PuzzleScript\compile.js:53:12
    at cb (d:\MyDocs\dev\Polyomino\PSForks\(increpare)PuzzleScript\node_modules\ncp\lib\ncp.js:255:37)
    at WriteStream.<anonymous> (d:\MyDocs\dev\Polyomino\PSForks\(increpare)PuzzleScript\node_modules\ncp\lib\ncp.js:133:14)
    at Object.onceWrapper (node:events:627:28)
    at WriteStream.emit (node:events:525:35)
    at finish (node:internal/streams/writable:748:10)
    at node:internal/streams/writable:726:13
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  path: 'd:\\MyDocs\\dev\\Polyomino\\PSForks\\(increpare)PuzzleScript\\bin\\images\\*.png',
  code: 'EINVAL'
}
```

Debugging shows that the illegal character is the '*'. My guess is it should be globbed, but isn't. Beyond that I have no idea.

### PR DESCRIPTION
**Pull request by david-pfx**
Fixes #955

### CODE REVIEW

**Comment by sftrabbit** [comment]
This needs `glob` to be pinned at a version before version 9. (I know you already know this @david-pfx, but I'm just adding it here for context).

For what it's worth, I think this PR would be easier to accept if it didn't also contain 2225ff6. That commit feels unrelated, and would require a bit more analysis to understand your approach to those fixes and whether there are better ways of achieving the same thing.

**Comment by david-pfx** [comment]
I tend to agree. I don't think I intended to combine them -- probably just my lack of familiarity with raising PRs. So I guess the plan is to raise two new PRs, and close this one?

**Comment by sftrabbit** [comment]
You could update this branch to only include 8ab9e04 by doing:

```sh
git checkout pr
git reset --hard 8ab9e04
git push -f
```

Then when you create a new branch for the other commit, you could do `git cherry-pick 2225ff6` to apply the content of that commit to your new branch.

**Comment by david-pfx** [comment]
Replaced by pr-ps-955 and pr-ps-932

**Pull request closed without merging**
