### PR TITLE
Improved autocomplete a bit

### PR DESCRIPTION
**Pull request by dario-zubovic**
puzzlescript rule autocomplete

### CODE REVIEW

**Comment by increpare** [comment]
Huh, thanks for the suggestion.

Not sure about how that feels. I think this'd only work as part of some very carefully thought out UX design rules-editing.  I'm not accepting it as is.   Also it doesn't support multiple cells / ellipses - but even if it did I don't think I'd be up for it? 

bildschirmfoto 2018-06-14 um 23 32 17

There's some auto-bracketing behaviour that some editors do that might be useful in puzzlescript - the sort where code editors insert closing braces for you, and you can tab past them, or if you try to enter right brace and theres already a right brace ahead of your character then nothing happens.  But it's super risky to do.  I dunno!

**Comment by increpare** [comment]
I think the closest you can get to the ghosting aesthetic with codemirror is to, when you add lots of text like that, to have all the tokens after the arrow be selected, so before if you have ```[ | ] -```, then after you have ```[ | ] -> [ | ]```, but where the "[ | ]" bit is now selected. Therefore, if you keep typing as usual it's just deleted.    I did this a bit with https://www.zeedonk.net/editor.html

**Comment by dario-zubovic** [comment]
Totally forgot about multiple cells! Automatically adding ... for ellipses would be useful too.

Should I work on such ghosting features if that's desirable?

**Comment by increpare** [comment]
I dunno what's desirable here (if you want to know what I desire from puzzlescript, there's a list here - https://github.com/increpare/PuzzleScript/issues :P ).  You're welcome to follow your heart, but I can't promise to accept any pull-requests.  I'm also happy to give feedback if you've a particular plan.

**Pull request closed without merging**
