### PR TITLE
More readable font

### LINKED ISSUE #199: try higher-resolution font
The legibility of the current one is so awful.

### PR DESCRIPTION
**Pull request by sfiera**
Fixes #199. Aesthetically, I've tried to keep the focus on 5x5 squares. That's why many capital letters (e.g. E, H, S, R) have their line above the midpoint. Here are a few games to try with a fair bit of text in them:

Take Heart Lass ([old font](http://www.puzzlescript.net/play.html?p=6902186), [new font](http://sfiera.github.io/PuzzleScript/play.html?p=6902186))
Sokobond: The Demake ([old font](http://www.puzzlescript.net/play.html?p=7005648), [new font](http://sfiera.github.io/PuzzleScript/play.html?p=7005648))
Aperture Science Sokoban Testing Initiative ([old font](http://www.puzzlescript.net/play.html?p=7511684), [new font](http://sfiera.github.io/PuzzleScript/play.html?p=7511684))
Kettle ([old font](http://www.puzzlescript.net/play.html?p=6878681), [new font](http://sfiera.github.io/PuzzleScript/play.html?p=6878681))
Character Sets ([old font](http://www.puzzlescript.net/play.html?p=af39ffae5e027f34c00a), [new font](http://sfiera.github.io/PuzzleScript/play.html?p=af39ffae5e027f34c00a))

I think it would be pretty easy to add a preamble option to pick a font, but I didn't do it.

### CODE REVIEW

**Comment by increpare** [comment]
random note to self backward compatibility consideration - this changelist
has sensitive text so it may make a bunch of previous games have weird
capitalization

**Comment by increpare** [comment]
I needed just a wee bit of time to mull this over, but yeah I've decided it's a good idea (I wanted to add accented characters and that's just not possible with the old one).  Have manually merged into main because I wanted to make a bunch of adjustments.

**Comment by increpare** [comment]
also: thanks!

**Comment by sfiera** [comment]
Oh, cool. I hadn’t thought about this in a long time.

I sent you https://github.com/increpare/PuzzleScript/pull/575 which fixes one character

And I updated https://www.puzzlescript.net/play.html?p=af39ffae5e027f34c00a to show off the accented characters (maybe all of them?) and more symbols (not all of them though).

**Pull request closed without merging**
