### PR TITLE
Clarify the need for loops in rigidbodies.html

### PR DESCRIPTION
**Pull request by Brinsky**
I'm suggesting this because it took a lot of rereading and head scratching for me to understand why cancelling all movement associated with a rigid rule(group) could cause a problem.

### CODE REVIEW

**Comment by Brinsky** [comment]
After I thought about it a bit more, I realized the example I proposed doesn't actually work (try pushing towards the left in https://www.puzzlescript.net/play.html?p=0813b87d6d4be41f494cafe2d7ece8df).

Given that limitation, I'm left still scratching my head about why
```
startloop

    <group A w/ rigid>

    <group B w/ rigid>

    <group C w/ rigid>

endloop
```
is significantly better than
```
<group A w/ rigid>
+ <group B w/ rigid>
+ <group C w/ rigid>
```
I guess with the former you could have a "clone" push block type B even if the player can't push block type A successfully on the same turn. Or maybe a better example - you couldn't have a bunch of non-adjacent rigidbodies made up of the same object with "gravity" being applied to them independently.

Can you give me an example where approach 1 above was essential to a game and approach 2 wouldn't have worked? I'd be especially curious to know if that's true even for the pictured example [from the documentation](https://www.puzzlescript.net/Documentation/rigidbodies.html):

Example from documentation

**Comment by increpare** [comment]
[ Thanks for the remark. I do plan on answering this properly, but I need
to be in a particular mindset to talk about rigidbody stuff, so can't
promise to reply punctually. ]

Am Di., 30. Nov. 2021 um 02:09 Uhr schrieb Brian Stottler <
***@***.***>:

**Comment by Brinsky** [comment]
Thanks, no rush. I thought about this a bit more in the meantime and came to a couple conclusions:

- If you genuinely want 2+ separate rigidbodies in your level that don't immediately glue themselves together on contact, they should be based on separate objects
    - More generally, if you are writing `rigid` rules (even if they aren't "sticky" in a rigidbody sense) you should understand that one failed movement attempt will disable the corresponding rule(group) for the entire turn. If you want independent/simultaneous movement of multiple object instances, they likely need to be represented by different underlying objects
- One giant rule group (vs. a loop of per-rigidbody rule groups) should work unless you need your (2+) rigidbodies to receive unrelated motion on the same turn (e.g. gravity, conveyor belts, clones, whatever).

If your game depends on having 2+ separate rigidbodies made up of the same objects/properties and having them move independently/simultaneously, you probably need to avoid `rigid` and rely on special marker objects:
- When motion is applied to one of the objects in question, place a custom "movement" marker in that cell
- If one of the objects in a cluster/rigidbody of objects is attempting to move against an obstacle, place a "cancel" marker
- The cancel marker should spread to wherever there is an adjacent movement marker
- Remove all motion attempts on objects sharing a cell with a cancel marker
- Acknowledge that your objects will get glued together (assuming you are writing traditional rigidbody movement rules) if they ever come in contact

---

I'm not sure any of that is worth distilling into the documentation (and most of it is already reflected there in one way or another). I'm guessing some games (like the GIF pictured above?) would be just fine having a single giant rule group and no loop, but trying to make that distinction might not be worthwhile.

**Comment by Brinsky** [comment]
Actually, I think my proposed change still captures the essence of the rationale for loops here, despite my waffling on whether reusing the same underlying object for different rigidbodies makes sense. I've tweaked the wording and the example slightly but otherwise I think it provides some extra clarity.

**Comment by increpare** [comment]
>I guess with the former you could have a "clone" push block type B even if the player can't push block type A successfully on the same turn.

This is exactly the kind of thing I was talking about, yeah.  (Gravity example also works).

> If you genuinely want 2+ separate rigidbodies in your level that don't immediately glue themselves together on contact, they should be based on separate objects

That's not always the case either.  There's a different way to approach extended bodies where have a base "block" object but overlay it with information about what adjacent blocks its connected to - see https://www.puzzlescript.net/editor.html?hack=079540a47d3e824cc3bd76cbd9aa24b3

I'm rewriting the rigidbody stuff from scratch right now (cf #864), and I'll basically try to incorporate something that responds to your point of confusion directly, kinda like your pull-request does.  Thank you for the useful question, and for taking time out to answer it yourself and suggest improvements.  It's very helpful.

(It's also useful for me right now to see someone asking questions about this because I'm redoing the documentation).

**Comment by Brinsky** [comment]
Cool, glad it helped. Thanks for taking the time to follow up - I'll take a look through the new docs in detail when I get a chance.

**Pull request closed without merging**
