### PR TITLE
Create non-anonymous Gists using a proxy

### LINKED ISSUE #431: Github removing anonymous gist creation
Yesterday, Github posted “[Deprecation notice: Removing anonymous gist creation](https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation)”:
> March 19, 2018 19:00 UTC (11:00 am PST): Disable anonymous gist creation via the web and API.

So if I understand correctly, PuzzleScript’s “Share” button is going to break in one month. One fix would be to add authentication (#306).

(I’d like to volunteer, but don’t think I’d get to it before the one-month deadline)

### PR DESCRIPTION
**Pull request by philschatz**
Fixes #431, refs #433.

This creates a little server so you can create authenticated Gists without allowing others to do things on your behalf (by keeping the `GITHUB_TOKEN` hidden).

You can try it out by doing the following:

1. Go to https://puzzlescript.herokuapp.com
1. Click the `[Make a Game]` button
1. Click the `[share]` link
1. Go to https://gist.github.com/philschatz and verify that the Gist was created (it will probably say "Created a few seconds ago")
    - This is currently tied to my account because of the `GITHUB_TOKEN` that was used

I used Heroku but there are many other providers that will host a web application. However, below are some advantages/disadvantages:

### Advantages

1. whenever the `master` branch changes, the website is automatically updated
1. whenever someone submits a Pull Request, heroku will start up a [Review App](https://devcenter.heroku.com/articles/github-integration-review-apps) so you can try out the changes before choosing to merge the Pull Request
1. you can host http://puzlescript.net for free (Note: `http://`, not `https://`)
    - this might be a problem because Google does not like `http://` anymore
1. you could _probably_ host just the uploader for free at https://puzzlescript.herokuapp.com by doing the following:
    - change `https://api.github.com/gist` to `https://puzzlescript.net/save` in `toolbar.js`
    - change `"application/x-www-form-urlencoded"` to `"application/json"` in `toolbar.js`

### Disadvantages

1. hosting `https://puzzlescript.net` (Note: `https://`) is not free but should cost about $7/month (See [Hobby Pricing](https://www.heroku.com/pricing))

### CODE REVIEW

**Comment by increpare** [comment]
Oh wow, this is a bunch of work. I appreciate it, but I have doubts.

I feel like this could be against their terms of service, and also, if someone posts child porn or whatever then the whole account could get shut down and everything would be lost?

**Comment by philschatz** [comment]
Oh no worries, I was working on Heroku for another project so it was fresh on my mind.

By the way, **Thank you for making wonderful games and enabling others to make great games**! Stephen's Sausage Roll and English Country Tune are my absolute favorites, and I got hooked on these types of games after stumbling upon puzzle-script.net

**Comment by philschatz** [comment]
RE Posting malicious Gists, I think the user's submission _could_ be validated as a valid puzzlescript file but the approach in #433 could work too (if you trust https://twotaled.com).

**Comment by philschatz** [comment]
Closing in favor of #433

**Pull request closed without merging**
